# Generated by Django 5.2.9 on 2025-12-17 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('goal', models.TextField()),
                ('domain_expertise', models.TextField()),
                ('debate_style', models.TextField()),
                ('backstory', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('is_system_agent', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs_app.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('final_dission', models.TextField(blank=True, null=True)),
                ('agents', models.ManyToManyField(blank=True, null=True, related_name='debates', to='core_app.agent')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMModelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=255)),
                ('input_messages', models.JSONField(default=list)),
                ('output_response', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_model_logs', to='core_app.agent')),
                ('debate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_model_logs', to='core_app.debate')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs_app.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_model_logs', to='core_app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='debate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='core_app.project'),
        ),
        migrations.AddField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core_app.project'),
        ),
        migrations.CreateModel(
            name='DebateMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_memory_disabled', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core_app.agent')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core_app.debate')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs_app.organization')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('debate', 'order')},
            },
        ),
    ]
